### PR TITLE
Support for interest rate

### PR DESCRIPTION
**Pull request by avclarke**
### Description

Support for interest rate changes in the latest snx perps upgrade

### CODE REVIEW

**Review by wangyangjun — COMMENTED** [review]
It seems the abi structure of `PerpsV3MarketProxy.json` is changed. The original one is a list of abi, while the updated version is like following. Other abi files all have similar structure as the original version of `PerpsV3MarketProxy.json`. Is this change intentional?
```
{
  "address": "0xE6C5f05C415126E6b81FCc3619f65Db2fCAd58D0",
  "abi": []
}
```

**Review by wangyangjun — COMMENTED** [review]
I guess we might want update the address here and still keep the original abi file structure?
-- https://github.com/Kwenta/kwenta-subgraph/pull/181/files#diff-e298c2da6b64bc78835bb27381c6b0b28732199237fe5e349c788ade786f91d7R10

**Comment by avclarke** [comment]
> It seems the abi structure of `PerpsV3MarketProxy.json` is changed. The original one is a list of abi, while the updated version is like following. Other abi files all have similar structure as the original version of `PerpsV3MarketProxy.json`. Is this change intentional?
> 
> ```
> {
>   "address": "0xE6C5f05C415126E6b81FCc3619f65Db2fCAd58D0",
>   "abi": []
> }
> ```

Yea will remove this, it doesn't seem to make a difference as I don't think this address is used and the abi is still picked up but it's inconsistent and confusing.

**Review by wangyangjun — APPROVED** [review]
Looks good

**Pull request merged**
